const assert=require('node:assert/strict');
const fs=require('node:fs');const path=require('node:path');
const {S,sandbox,run,setTime,getEl,storageData}=require('./core-harness');
assert.ok(fs.existsSync(path.join(__dirname,'../practice.js')), 'practice engine must exist');
run(fs.readFileSync(path.join(__dirname,'../practice.js'),'utf8'));
const practice=sandbox.window.TetrisPractice;
run(`game=new Tetris({...SOLO_CONFIG,bag:new SeededBag7(123)});game.spawn();currentMode='solo';running=true;isPaused=false;`);
setTime(1000); practice.capture();
assert.equal(practice.count,1,'capture at valid piece entry');
const original=run(`JSON.stringify({grid:game.grid,queue:game.nextQueue,piece:game.piece.type,hold:game.hold})`);
const future=run(`Array.from({length:70},()=>game.bag.next()).join('')`);
run(`game.grid[19].fill('j');game.hold='T';game.score=100000;game.over=true;running=false;`);
assert.equal(practice.retry(0),true);
assert.equal(run(`JSON.stringify({grid:game.grid,queue:game.nextQueue,piece:game.piece.type,hold:game.hold})`),original,'exact board/queue/hold/piece restored');
assert.equal(run(`Array.from({length:70},()=>game.bag.next()).join('')`),future,'70 future pieces repeat across bag boundaries');
assert.equal(practice.active,true);
run(`game.over=true;game.score=900000;endSolo();`);
assert.equal(storageData['tb-high-score'],undefined,'practice never writes high scores');
assert.equal(practice.retry(0),true,'same checkpoint can be repeated');
run(`currentMode='online';running=false;`);
assert.equal(practice.retry(0),false,'online matches cannot rewind');
practice.reset();setTime(2000);
run(`currentMode='battle';currentDifficulty='easy';running=true;game=new Tetris({...BATTLE_PLAYER_CONFIG,bag:new SeededBag7(4)});aiGame=new Tetris({...BATTLE_AI_CONFIG,bag:new SeededBag7(5)});game.spawn();aiGame.spawn();ai=new TetrisAI(aiGame,'easy');battleManager=new BattleManager(game,aiGame);game.isLocking=true;game.lockStartTime=1850;game.lastTime=1900;ai.thinking=true;ai.thinkStart=1800;ai.lastActionTime=1700;game.receiveGarbage(2,true);`);
practice.capture();
assert.ok(run('game.randomSource && ai.randomSource'),'independent gameplay random streams are snapshot-able');
const branch=()=>run(`JSON.stringify({garbage:(game.insertGarbageRows(2,true),game.grid),plans:Array.from({length:8},()=>ai.computeBestMove())})`);
const expected=branch();
run(`game.over=true;running=false;`);setTime(9000);
assert.equal(practice.retry(0),true);
assert.equal(run('game.lockStartTime'),8850,'remaining lock-delay rebased, not instant topout');
assert.equal(run('game.lastTime'),8900,'gravity age restored');
assert.equal(run('ai.thinkStart'),8800,'CPU remaining thought delay restored');
assert.equal(branch(),expected,'identical garbage holes, bombs and CPU mistake choices');
practice.reset();run(`running=true;currentMode='solo';game=new Tetris({...SOLO_CONFIG,bag:new SeededBag7(6)});`);
for(let i=0;i<25;i++){run('game.spawn()');practice.capture();}
assert.equal(practice.count,12,'bounded in-memory history');
console.log('PASS exact retry, future bags, score isolation, online guard, CPU/garbage RNG, timers, bounded history');
